### ISSUE TITLE
/jira instance install server <jira-url> failed 

### ISSUE THREAD

**Issue by rogerhsu1121** [mattermost/mattermost-plugin-jira#932] opened 2023-04-07 10:51 UTC
My Mattermost is Mattermost Enterprise Edition
Mattermost Version: 7.3.0
Database Schema Version: 92
Database: mysql

and JIRA Plugin Version is Jira (jira - 3.2.4)

but when I am trying to install JIRA on Mattermost channel.

/jira instance install server <jira-url>

It shows
	
jira BOT 6:07 PM(Only visible to you)
You need a valid Mattermost E20, Professional, or Enterprise License to install multiple Jira instances.

**Comment by jprusch** [comment] 2023-04-07 11:28
Enterprise Edition doesn't mean Enterprise license... Did you buy an enterprise license? If not, you can connect to a single Jira server only.
Please check, if a Jira instance is already connected with /jira info

**Comment by rogerhsu1121** [comment] 2023-04-10 02:30
> Enterprise Edition doesn't mean Enterprise license... Did you buy an enterprise license? If not, you can connect to a single Jira server only. Please check, if a Jira instance is already connected with /jira info

Right, I didn't buy enterprise license. 
I check /jira info

Mattermost Jira plugin version: 3.2.4, 05bf60b, built Mon Mar  6 05:51:42 PM UTC 2023.

Mattermost site URL: https://mattermost.example.com
Mattermost user ID: jwqp6konmbnhbbz77wh5yn4exx
Jira is installed, but you are not connected. Please type /jira connect to connect.

Available Jira instances:
https:/jira2.xxx.com: server (aHR0cHM6Ly90cGUtamlyYTIuZmlodGRjLmNvXXXX)

I just wanna connect a single Jira server.
Should I use this command?
/jira instance install server https:/jira2.xxx.com

But it response
You need a valid Mattermost E20, Professional, or Enterprise License to install multiple Jira instances.

Thanks your reply....

**Comment by jprusch** [comment] 2023-04-10 05:43
It seems that Jira is installed already.
Did you try /jira connect?

**Comment by rogerhsu1121** [comment] 2023-04-10 06:03
> It seems that Jira is installed already. Did you try /jira connect?

I try 
/jira instance connect https://jira2.xxx.com
or
/jira  connect https://jira2.xxx.com

it popup another browser tab and shows

> failed to get a connect link: oauth1: Server returned status 401

I think that due to I didn't finish /jira install server step,  didn't get PUBLIC KEY to paste to JIRA setting page.

I follow the SOP steps 6. from 
https://cloud.tencent.com/developer/article/1639840
> 
> 6.In the following Link Applications screen, set the following values:
> Consumer Key: mattermost_http_mm_idevops_site
> Consumer Name: Mattermost
> Public Key: -----BEGIN PUBLIC KEY-----
> MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2mbXCqNvhulHf4Ls7Pi88kcC8
> DClduz1Otaf04INVUlPO7c/NyDqV+0N4SbJsf69DFU0zmJ+8owfqeNLINxSoTmOw
> JzZ8KLFAxZ/jAY46R6ad91aS86XS7vRBBuAZGMSPyt3dW1kFe05ZQ3t+OAcFYUSN
> og87n+neJaGOnGmoRwIDAQAB
> -----END PUBLIC KEY-----

**Comment by rogerhsu1121** [comment] 2023-04-10 07:02
> It seems that Jira is installed already. Did you try /jira connect?

I found I didn't get PUBLIC KEY and the other configurate information,
so I use /jira uninstall server https://jira2.xxx.com
then I enter /jira install server https://jira2.xxx.com again.
I get the PUBLIC KEY and the other information. 
Now I pass those information to our JIRA website administrator to paste those info to JIRA setting page then go on.

Thanks

**Comment by mickmister** [comment] 2023-04-10 16:12
Hi @rogerhsu1121, thanks for reporting this issue. It's unclear to me if the issue is still occurring based on your last comment. Were you able to get this issue resolved? Thank you

**Comment by raghavaggarwal2308** [comment] 2024-07-18 11:02
@rogerhsu1121 We are closing this issue for now. Please let us know if you are still facing any issues.

**Closed by raghavaggarwal2308** 2024-07-18 11:02 UTC
Labels: Type/Bug
