### ISSUE TITLE
Title partially unrendered when it contains a backtick

### ISSUE THREAD

**Issue by agarciamontoro** [mattermost/mattermost-plugin-jira#584] opened 2020-06-08 18:05 UTC
I got a notification regarding a ticket with the title
```
Something like a `BackstageManager` / `IncidentRouter` to switch the backstage focus
```

The direct message from the Jira bot did not contain any of the characters following the first backtick in the title:

![image](https://user-images.githubusercontent.com/3924815/84064657-4932bc00-a9c3-11ea-85eb-4978bfebf458.png)

**Comment by mickmister** [comment] 2020-06-18 02:01
I think this may be caused by https://mattermost.atlassian.net/browse/MM-25808 . @agarciamontoro do you mind copy and pasting the markdown for that post in a comment here? By using the three dot post dropdown menu `Copy` option

**Comment by mickmister** [comment] 2020-06-18 08:33
@agarciamontoro Confirmed that is the issue. The fix will be in the next mattermost-webapp dot release

**Closed** 2020-06-18 08:49 UTC
Labels: Invalid
