### ISSUE TITLE
Quotes within a Jira comment do not display correctly

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#599] opened 2020-07-22 13:59 UTC
When adding quotes within a comment using the editor and saving from the new Jira view, the quotes do not display correctly in Mattermost.
![Screen Shot 2020-07-22 at 9 15 27 AM](https://user-images.githubusercontent.com/35588783/88185247-b6ac4c00-cc01-11ea-9070-228ef5ee8329.png)

When editing the comment in the Jira UI, it seems the raw text is different and are webhook is correctly sending the raw 
text.

![Screen Shot 2020-07-22 at 9 51 05 AM](https://user-images.githubusercontent.com/35588783/88185273-be6bf080-cc01-11ea-8de3-70dc1aedf37e.png)
![Screen Shot 2020-07-22 at 9 51 46 AM](https://user-images.githubusercontent.com/35588783/88185284-c1ff7780-cc01-11ea-9da4-cffb57d7a15c.png)

Steps:
- Install a Jira cloud instance a create a webhook that includes new comments
- Open target jira issue in the new view (ensure URL does not have _?oldIssueView=true_) appended
- Type a comment 
- Add a quote using the formatting from the WYSIWYG
- Save

**Observed**: Quotes show as `{quote}` which seems to be the raw text when the new view wants to render quotes.

**Comment by Kshitij-Katiyar** [comment] 2023-03-07 08:31
@DHaussermann @hanzei  I am able to reproduce this issue but I am not able to change to the old issue view in my instance maybe jira discontinued that. Secondly, this kind of bug for formatting is not just for quotes, I am able to find a bunch more like 
1) Bold in jira. If I bold a word in jira, in mm it comes as italics. 
![Screenshot from 2023-03-07 13-51-31](https://user-images.githubusercontent.com/90389917/223365076-9633083f-a265-4d46-800d-fcfc3087ee7a.png)
![Screenshot from 2023-03-07 13-51-12](https://user-images.githubusercontent.com/90389917/223365104-ed2fbf79-c43a-42ec-863d-8b9062cf1f46.png)

2)Code block in jira. If I comment using a code block in jira, in mm it comes with {noformat} tag.
![Screenshot from 2023-03-07 13-56-00](https://user-images.githubusercontent.com/90389917/223365921-12d6aaba-0b03-4261-b14e-798cd80818d2.png)
![Screenshot from 2023-03-07 13-55-47](https://user-images.githubusercontent.com/90389917/223365939-5c7348d6-cd53-47c2-84ce-960de5fe8abf.png)

There can be many more examples like these. From my understanding the only solution for this would be when we get the webhook event we can extract its body and create a regex to handle all these examples (it's very difficult as we don't know all the cases) first extract the tags and replace them with the supported versions in mattermost.

If you have any insights or suggestions please feel free to answer them.

**Comment by DHaussermann** [comment] 2023-07-17 15:59
@Kshitij-Katiyar ya the issue is quite old. I'm not surprised at all that "_old issue view in_" is no longer available in Cloud.  

Yes it possible alot of mark down is affected.

**Comment by Kshitij-Katiyar** [comment] 2023-07-20 16:28
@DHaussermann @hanzei But the difference still persists in the markdowns. Can you please share your views on how to fix them as there are many unknowns here and how to fix them.

**Comment by mickmister** [comment] 2023-08-02 11:37
@Kshitij-Katiyar There are some open (technically closed) issues for Jira & Mattermost markdown compatibility:

- https://github.com/mattermost/mattermost-plugin-jira/issues/147
- https://github.com/mattermost/mattermost-plugin-jira/issues/148

As well as an (I believe abandoned) effort to solve this holistically with https://github.com/nathanmkaya/goldmark-extended mentioned here https://github.com/mattermost/mattermost-plugin-jira/issues/147#issuecomment-568272983. I think that solution is a large undertaking, and I'm thinking we shouldn't go down that route, though just sharing here for completeness.

In general, we've viewed this as "won't fix", since there are so many differences between Jira's formatting and common uses of markdown. We can treat each finding individually and solve them case-by-case, but I don't think the effort is warranted to devote dev cycles on these particular issues at the moment. Personally, I think these individual findings would be good as separate HW tickets for contributors to work on.

**Closed** 2024-09-10 11:16 UTC
Labels: Triage, Type/Bug
