### ISSUE TITLE
cannot unmarshal string into Go struct field JiraWebhook.comment of type jira.Comment

### ISSUE THREAD

**Issue by cadavre** [mattermost/mattermost-plugin-jira#385] opened 2019-11-14 18:07 UTC
While receiving webhook from Jira:

```
cannot unmarshal string into Go struct field JiraWebhook.comment of type jira.Comment
```

**Comment by levb** [comment] 2019-11-19 14:54
@cadavre from https://github.com/mattermost/mattermost-plugin-jira/issues/384, assuming you are using a Jira Cloud set up?

**Comment by cadavre** [comment] 2019-11-19 15:01
@levb correct.

**Comment by crspeller** [comment] 2019-11-20 00:37
@cadavre 
1. Is the error you are seeing the the Mattermost logs?
2. Does it cause the plugin to not work? Or is it just an error.
3. Can you confirm how you have setup the webhook from JIRA. A screenshot of the webhook admin panel would be good.

**Comment by cadavre** [comment] 2019-11-20 15:32
1. Mm logs.
2. Plugin works with Bot notifying me on new comments watched by me. Works with command.
3. I configured Jira webhook to call my Mattermost instance.

ad 2) Just Jira webhooks are parsed with this error.

**Comment by crspeller** [comment] 2019-11-26 21:52
@cadavre I can not reproduce with a real JIRA server.
Is there any chance that something else is making requests to the webhook endpoint? That could be the cause.

**Comment by levb** [comment] 2020-01-14 18:27
Not repro

**Comment by hanzei** [comment] 2021-06-30 13:53
Closing as can't repo

**Closed by hanzei** 2021-06-30 13:53 UTC
Labels: Type/Bug, Wontfix
