### ISSUE TITLE
Not able to connect to a Jira cloud instance

### ISSUE THREAD

**Issue by Kshitij-Katiyar** [mattermost/mattermost-plugin-jira#945] opened 2023-05-30 11:39 UTC
After running the slash command ```/jira instance connect <instanceURL>``` or in case of a single instance ```/jira connect```. I am getting the error 
```
could not get user info for client, err: No response returned: Get "https://<url>.atlassian.net/rest/api/2/myself": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid aud: https://auth.atlassian.io"}
```

Steps to reproduce:- 
1) Install the instance by running the command ```/jira instance install cloud <url> ```.
2) Upload the app on the Jira cloud instance.
3) Run /jira connect and click on the URL.

mattermost server version - 6.6

**Comment by serve-id** [comment] 2023-05-30 13:46
**exact same Problem here - was working smooth before Plugin Update:** 

Steps to reproduce:-
Install the instance by running the command /jira instance install cloud <url> .
Upload the app on the Jira cloud instance.
Run /jira connect and click on the URL.
mattermost server version - Version: 7.7.1
DB-schema-Version: 100
Jira-Plugin-Version:  3.2.5

**Comment by mickmister** [comment] 2023-05-30 15:17
@Kshitij-Katiyar What is shown to the user in the browser when this happens? Is there a tab that navigates to Jira's site?

**Comment by Kshitij-Katiyar** [comment] 2023-05-30 15:24
@mickmister This is the error I am getting here. Please find the video below for more understanding:-
[jira-error.webm](https://github.com/mattermost/mattermost-plugin-jira/assets/90389917/18a566d9-5905-470c-ae37-cfa27e2674ca)

**Comment by mickmister** [comment] 2023-05-30 17:34
Thanks @Kshitij-Katiyar :+1:

I'm not sure exactly what the problem is here. If we can't figure it out with a little debugging, and it reproduces on every setup, we may need to go down the path of deprecating the Atlassian Connect method of authentication.

We've been wanting to deprecate the Atlassian Connect method for a while, which is currently how the user authentication with Jira Cloud works in the plugin. The alternative is to use Jira's OAuth2.0 offering, which we have implemented in a PR https://github.com/mattermost/mattermost-plugin-jira/pull/928 that was closed due to change in priorities.

The author of that PR is no longer working on the project, so the PR will need to be picked up again and driven to be merged. The PR has been dev approved, and has some remaining concerns from QA here https://github.com/mattermost/mattermost-plugin-jira/pull/928#issuecomment-1538466665.

@Kshitij-Katiyar What are your thoughts on getting the OAuth2 PR merged and shipped, to resolve the ticket you've created here? cc @hanzei @DHaussermann

**Comment by mickmister** [comment] 2023-05-30 17:36
It's also possible this is a regression on Jira's side, or possibly a deprecation we were unaware of for an API we are using. A quick search for this error isn't yielding much information, but maybe there is more information to be found.

**Comment by mickmister** [comment] 2023-06-01 15:49
@Kshitij-Katiyar With some testing I've confirmed that using OAuth 2 via https://github.com/mattermost/mattermost-plugin-jira/pull/928 sidesteps the issue. Are you able to pick this PR up? This issue is particularly urgent, as it seems no Jira Cloud instances can be connected to at the moment.

**Comment by Kshitij-Katiyar** [comment] 2023-06-02 11:24
> @Kshitij-Katiyar With some testing I've confirmed that using OAuth 2 via #928 sidesteps the issue. Are you able to pick this PR up? This issue is particularly urgent, as it seems no Jira Cloud instances can be connected to at the moment.

@mickmister sure will pick this up

**Comment by Kshitij-Katiyar** [comment] 2023-06-02 11:39
> @Kshitij-Katiyar With some testing I've confirmed that using OAuth 2 via #928 sidesteps the issue. Are you able to pick this PR up? This issue is particularly urgent, as it seems no Jira Cloud instances can be connected to at the moment.

@mickmister I noticed that ou pushed some commits on PR https://github.com/mattermost/mattermost-plugin-jira/pull/928

**Comment by mickmister** [comment] 2023-06-02 15:23
@Kshitij-Katiyar I was mainly resolving merge conflicts. I'm not able to own the PR going forward though because I'm going on PTO for the next few weeks.

**Comment by mickmister** [comment] 2023-06-02 15:25
@Kshitij-Katiyar Feel free to give the PR a review to get a better understanding of what is implemented there

**Comment by mickmister** [comment] 2023-06-02 15:32
@Kshitij-Katiyar Maybe this is another way around this while still using Atlassian Connect. Is there any other info you were able to uncover about the issue?

**Comment by mickmister** [comment] 2023-06-05 22:54
@Kshitij-Katiyar Note that I've closed that PR https://github.com/mattermost/mattermost-plugin-jira/pull/928 since the developer is not working on the project, and reopened it as https://github.com/mattermost/mattermost-plugin-jira/pull/949

**Comment by Jawknee-cache** [comment] 2023-07-19 19:52
Is there currently a workaround for this issue?

**Comment by mickmister** [comment] 2023-07-19 20:08
Hi @Jawknee-cache, currently there is no workaround. Once https://github.com/mattermost/mattermost-plugin-jira/pull/949 is merged and released, then this should be resolved. We apologize for this inconvenience.

**Comment by BlueSky-fur** [comment] 2023-07-21 16:07
Glad this finally gets more traction, seems like people are struggeling with this since around 2020.

Since Omnibus updates take even longer, i guess regular instances get the update quicker?

**Comment by mickmister** [comment] 2023-07-21 16:20
> Since Omnibus updates take even longer, i guess regular instances get the update quicker?

@BlueSky-fur Once a new version of the plugin is released, you'll be able to update the Jira plugin on your Omnibus installation immediately

**Comment by BlueSky-fur** [comment] 2023-07-21 18:04
Oh its a plugin update! That makes it so much more awesome! :D 

Thanks for the info!

**Comment by obi12341** [comment] 2023-08-11 19:12
we have exactly the same problem which is preventing us from migrating our gitlab/omnibus team edition to the already paid standalone kubernetes operator premium edition. Is there any ETA for this issue? By the way our team edition is working fine and reinstalling works fine but on the seperate premium edition with exactly the same Jira Cloud Instance we are facing this issue, which makes me belive it is not an jira issue. Maybe related to the Reverse Proxy Configuration or something like that?

**Closed** 2023-08-29 21:49 UTC
Labels: Type/Bug
