### ISSUE TITLE
Prompt MM user to resolve ticket when their Github PR is merged

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#342] opened 2019-10-10 15:58 UTC
#### Summary

The basic idea for this feature is:

- A PR gets merged
- For any related Jira tickets that now need to be resolved, the assignee on the associated Jira ticket should receive a DM to resolve the ticket within MM.

This removes the delay of a ticket waiting in the `Submitted` stage before it is resolved.

#### Technical Steps

We would need to set up a authentication between Github and the Jira plugin. We could get the Github plugin involved, though all we really want to know is when a PR is merged (this could work for PR opened as well).

- Jira plugin is authenticated with Github
- Jira plugin receives event for PR getting merged
- Jira plugin parses the PR description to look for tickets
- Jira plugin sees if any of those tickets are in the `Submitted` state (we may want to relax this requirement for simplicity of the initial implementation here)
- For each that match that criteria, get the assignee. If he/she is connected to MM with the plugin, send them a message like:

`This PR was just merged (link), would you like to resolve this ticket (link)?`

The DM then serves as a "todo" to get the ticket resolved. It's alright to have false positives (like the associated ticket wasn't actually ready to be resolved etc)

-----

#### Future Plans

Ideally you can resolve inside of MM (that's why this is going in this plugin vs the Github plugin), but that is out of scope of this ticket. That would require analysis of the transition steps based on the Jira workflow configured.

For discussion, I believe we can gather this using the method described here: https://community.atlassian.com/t5/Jira-questions/Get-Required-mandatory-transition-fields-using-REST-API/qaq-p/594308

-----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by enolal826** [comment] 2019-10-21 12:17
Hello @mickmister! I'd like to work on this.

It's my first contribution to the Mattermost project though so it's going to take me some time to get to know the code and implement the feature.

Is there any rush? Thanks!

**Comment by mickmister** [comment] 2019-10-21 13:59
@enolal826 Thank you for wanting to work on this! There is no rush. Feel free to ask questions on the community server. You can message me directly on there too `@michael.kochell` :+1:

**Comment by mickmister** [comment] 2019-10-21 15:53
@enolal826 I thought I'd put some info here for reference.

We'll likely borrow some concepts from how the github plugin is authenticating with github https://github.com/mattermost/mattermost-plugin-github#step-1-register-an-oauth-application-in-github . Looking through the github plugin codebase may be useful in learning how the github webhooks are set up.

**Comment by enolal826** [comment] 2019-10-21 16:37
Ok, I'll have a look at the Github plugin. Thanks!

**Comment by mickmister** [comment] 2019-10-23 16:36
Another event that might be helpful to handle is when a PR is opened, the user can be prompted to move the ticket to "Submitted". I'm thinking there needs to be some configuration, like having the sysadmin choose the different Jira statuses that exist in their system that should be used for each situation.

I don't want to increase the scope of this task though, as there is already plenty of foundation to work off of in this ticket.

**Comment by enolal826** [comment] 2019-11-11 18:19
Getting back to this issue. I'd like some discussion on my approach:

We are gonna be working with both Github and Plugin repos using the new plugin communication feature.

Github:
1. Getting PR event
2. Looking for MM tickets in the PR description
3. Jira Plugin request in order to close parsed tickets

Jira:
1. Getting HTTP request on route /issue-close with query params: ?issues=1,2,3 and ?askAssignee=true/false (this way, the endpoint could be reused in the future and "ask assignee" becomes just an option)
2. Retrieving MM issues through the Jira client (*)
3. Finding issues' assignees
4. Asking issue assignee wether he/she wants to close it

(*) The problem is that we need to authenticate a user in order to retrieve the issues through the Jira client, so we need to pass a Mattermost-User-Id from the GitHub plugin scope. Which one? From the Github PR event we have:
	- Action performer
	- PR owner
	- Reviewer(s)

Ideally, we would pass the Assignee user id and in case the user is not authenticated with the Jira plugin, we would simply not perform the action, but we don't know who the assignee is at that stage.

What options can you see for this? We might assume the creator of the review must be the one who got assigned the ticket.

**Comment by mickmister** [comment] 2019-11-11 19:57
Sorry, I accidentally pressed close issue. Reopened.

> Github:
> 1. Getting PR event
> 2. Looking for MM tickets in the PR description
> 3. Jira Plugin request in order to close parsed tickets

I actually don't think the Github repo should be parsing the description for Jira issue links, because the organization's Jira domain could be anything. I think the Jira plugin should be purely subscribing to the Github plugin for PR merge events (could potentially be for PR open etc too). The Github plugin should be as decoupled from the Jira functionality as possible.

> The problem is that we need to authenticate a user in order to retrieve the issues through the Jira client, so we need to pass a Mattermost-User-Id from the GitHub plugin scope.

I think the creator of the PR is the right account to use here. Maybe the Github plugin makes a request like:

POST `plugins/jira/api/github-event?user_id={PR creator's mattermost user id}`, and the body would have the Github payload in it.

After the Jira plugin has parsed the body to determine any tickets involved, it can use either the assignee or PR creator to post a DM inside of MM. The good thing about using the PR creator instead of the assignee, is that we don't have to fetch any info on the issue. We can just message the PR creator `close this ticket: (link)`. It might be good to start with simplicity like this.

Once the feature is more advanced (see `Future Plans` in this issue's description), we will need to fetch the issue to gather things like Resolve Steps. For now, I think just posting the link to the PR creator is a great foundation.

@enolal826 Thanks for being so interested in this! What are your thoughts?

**Comment by enolal826** [comment] 2019-11-11 20:53
Yes, if we are gonna extend this feature in the future it would probably make more sense for the Jira plugin to just receive the GitHub event, but in that case I think we should just propagate the event without any query params, simply including all the information in the body, exposing just one endpoint (as a kind of webhook).

Anyway, should we manage wether the assignee actually wants to receive this kind of notifications? 
 The "subscribe" command allows you to receive specific notification for a channel, should we do the same for DM notifications?

Thanks!

**Comment by mickmister** [comment] 2019-11-11 22:39
@enolal826 I think it makes sense for the Github plugin to pass along relevant information that it knows through its kvstore entries. This includes the mapping of Github users and MM users. The Jira plugin otherwise cannot identify the Github users in the MM system.

We should definitely try to make this as general purpose as possible. Maybe the Github plugin can send `creator_id` and `assignee_id` (both MM user ids) or something of the sort. There may be other useful pieces of information that can be included.

>  I think we should just propagate the event without any query params, simply including all the information in the body, exposing just one endpoint (as a kind of webhook).

I think having a general purpose endpoint is the way to go. There should be a way for the Jira plugin to subscribe, without having the Github plugin to know anything about the Jira plugin.

**Comment by mickmister** [comment] 2020-01-22 15:39
Closing until we have an example available for a workflow `action` implemented, per https://github.com/mattermost/mattermost-plugin-jira/pull/403#issuecomment-576917165 .

**Comment by mickmister** [comment] 2020-02-12 17:02
We now have some examples available for plugin-to-plugin communication. We will not be using the workflow plugin here. Here are two PRs showing `Jira -> Autolink` plugin communication.
[Jira PR](https://github.com/mattermost/mattermost-plugin-jira/pull/453)
[Autolink PR](https://github.com/mattermost/mattermost-plugin-autolink/pull/85)

The task here will involve `GitHub -> Jira` plugin communication.

Reopening task and setting `Up for Grabs` since there are relevant examples now :+1:

**Comment by wiersgallak** [comment] 2023-06-14 01:27
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.

**Closed by wiersgallak** 2023-06-14 01:27 UTC
Labels: Help Wanted, Up For Grabs, Hacktoberfest, Tech/Go, Difficulty/2:Medium, Type/Enhancement
