### ISSUE TITLE
MM is unable to create a subscription if the JIRA project prevents cloning issues

### ISSUE THREAD

**Issue by wickhage077** [mattermost/mattermost-plugin-jira#885] opened 2022-10-28 14:30 UTC
When the running MatterMost plugin (Mattermost Jira plugin version: 3.2.0, built Tue Mar  1 20:50:32 UTC 2022.) and we try to  subscribe by selecting a project that stops you from cloning issues we get the following:
<img width="183" alt="Screenshot 2022-10-28 at 13 32 44" src="https://user-images.githubusercontent.com/74602172/198644514-ef0dab46-2b2a-4321-a796-ee0425ab071e.png">

<img width="938" alt="Screenshot 2022-10-28 at 13 33 23" src="https://user-images.githubusercontent.com/74602172/198644750-a94b6c8c-454a-4d8f-a476-504e8f70f3fc.png">

<img width="952" alt="Screenshot 2022-11-14 at 13 34 00" src="https://user-images.githubusercontent.com/74602172/201673502-f62d624f-e94b-44fa-ab50-afc5527f9c40.png">

**Comment by mickmister** [comment] 2022-11-08 18:36
@DHaussermann Can you please see if you can reproduce this?

**Comment by wickhage077** [comment] 2022-12-22 14:08
Any update?

**Comment by wickhage077** [comment] 2023-01-12 10:51
Hi Any update on this issue?

**Comment by mickmister** [comment] 2023-01-24 01:08
@wickhage077 This is currently waiting on @DHaussermann's analysis

@wickhage077 This may be an issue with your specific user's permissions. Do you have permissions to create issues in that project?

**Comment by wickhage077** [comment] 2023-02-22 11:29
Hi @mickmister , I am the jira sys admin so permission is not an issue.

Steps to reproduce/test
1. create a JIRA project (CRTST) with a simple workflow (TO-DO-> In Progress -> Done)
2. In MM, try
2.1 /jira subscribe
2.2 try selecting the CRTST project (and it will work)
3. Edit workflow
3.1 Click on each Status, in turn
3.1.1 Click the Properties link in the pane that pops up
3.1.2 Add a new property with the following values
3.1.2.1 Property Key: jira.permission.create.clone
3.1.2.2 Property Value: denied
4. Publish the workflow
5. In MM, try
4.1 /jira subscribe
4.2 try selecting the CRTST project (error will appear)

Hope this helps

**Comment by mickmister** [comment] 2023-02-23 17:54
@DHaussermann The issue author provided some steps that may work to reproduce this issue

**Comment by wickhage077** [comment] 2023-03-30 13:30
Hi @DHaussermann @mickmister @catalintomai, do you know when this will be fixed?

**Comment by wickhage077** [comment] 2023-03-30 14:11
@DHaussermann, We are currently running:
- JIRA Server v8.20.11, 
- Mattermost Version: 7.3.0
- Database Schema Version: 92
- Database: mysql
- Mattermost Jira plugin version: 3.2.0, [f986c15](https://github.com/mattermost/mattermost-plugin-jira/commit/f986c159ec37a6b1cf727840d8899f84a1aff612), built Tue Mar  1 20:50:32 UTC 2022 and

**Comment by raghavaggarwal2308** [comment] 2023-08-22 11:35
@mickmister The issue is occurring when we are making an [API call](https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-getCreateIssueMeta) to fetch the metadata (mainly the supported issue types on the project and the custom fields associated with those issue types) for displaying the subscription filters. If you read the discussion on [this ticket](https://jira.atlassian.com/browse/JRASERVER-67652), you will see that the `jira.permission.create.clone.denied` permission prevents the user from creating an issue (not just cloning the issues) because of which [the get create issue metadata API](https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-getCreateIssueMeta) is returning the error. I explored if there is any other API we can use to get the required data but I was unable to find any.
Please let me know if you have any suggestions!

**Comment by mickmister** [comment] 2023-08-22 15:49
Hi @raghavaggarwal2308, I got a message from you mentioning me on this issue. Are you still wanting to discuss this issue?

**Comment by raghavaggarwal2308** [comment] 2023-08-23 10:18
> Hi @raghavaggarwal2308, I got a message from you mentioning me on this issue. Are you still wanting to discuss this issue?

@mickmister No, nothing for now

**Comment by wickhage077** [comment] 2023-08-23 12:58
Hi both, I have raised a ticket with Atlassian to see if they can fix this issue as they allow the sourcing of issue types, but not the fields (meta)data.

Let’s see if we get anywhere, not that a fix is going to be quick, if applicable.

Rgds
Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raghavaggarwal2308** [comment] 2023-08-28 09:39
@mickmister I explored this issue. The issue was occurring when we were making an [API call](https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-getCreateIssueMeta) to fetch the metadata (mainly the supported issue types on the project and the custom fields associated with those issue types) for displaying the subscription filters. After reading the discussion on [this ticket](https://jira.atlassian.com/browse/JRASERVER-59487), I learned that the permission name `jira.permission.create.clone.denied` is not valid and the valid permission name is `jira.permission.createclone.denied`. Due to this invalid permission the Jira  API was returning an error, after changing the permission name the error vanished but the 'fields' details are not being sent in the response anymore. I tried to find the reason for the same but I was unable to find anything. There are many similar issues on Jira but none of them solves our problem.

**Comment by mickmister** [comment] 2023-09-07 15:10
@raghavaggarwal2308 What are you thinking are next steps here? From your comment it's unclear if there's any fix that we can do on our side

**Comment by wickhage077** [comment] 2023-09-08 13:33
Hi Raghav, the issue still exist with ‘jira.permission.createclone.denied.’, and Atlassian advice to exclude the users who need to retrieve the metadata, but that would mean removing the restriction.

Couple if things:

  1.  if ‘jira.permission.create.clone.denied’ is invalid then why is it in their drop-down?
  2.  If you try to get the issue type metadata then all is ok, but when you try to get the fields within each issue type then it fails
  3.  The workaround that I found is to use the legacy webhook, but it begs the quest Huw that works

Rgds

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mickmister** [comment] 2023-09-11 14:58
@wickhage077 What do you recommend we do on our end? If there is nothing to be done, I would like to close this issue if that's okay

**Comment by wickhage077** [comment] 2023-09-13 11:48
Hi, I was wondering if you could make a call to the webhook to get the metadata

Rgds

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mickmister** [comment] 2023-09-13 15:34
@wickhage077 I don't think that's possible but I'm not sure I understand what this means. What system will reach out to what system via webhook and fetch what metadata?

**Comment by wickhage077** [comment] 2023-09-13 15:54
Hi, I was just thinking about a workaround m, but Let’s close the ticket as the issue is really with Atlassian.

Rgds

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2023-09-13 16:58 UTC
Labels: Type/Bug
