### ISSUE TITLE
Multiple Jira projects in a single channel

### ISSUE THREAD

**Issue by Snipa22** [mattermost/mattermost-plugin-jira#328] opened 2019-10-01 20:45 UTC
Hello,

I'm working on a use-case where I'd like to have 2 or more projects from Jira funneled into a single channel for easy review of the content moving through Jira.  I know that I can get the task creations/etc through the V1 hook, but I can't seem to get comments working.  The JSON structure of the updated comment appears to be valid, and it's not throwing any logs/errors that can help me determine what's happening.

The new V2 system doesn't appear to allow me to subscribe more than one Jira project into a single channel.

Mattermost Version: 5.14.2 (GitLab Omnibus)
Plugin Version: 2.2.0
Jira Version: 8.4.0

Thanks for any help available!

**Comment by aaronrothschild** [comment] 2019-10-01 21:27
Hi @Snipa22 , Take a look at these designs on invision: https://projects.invisionapp.com/share/QZQIQ9YKH9T#/screens/381769985 and let me know if it would suit your use case.  Any feedback is welcome.  @jfrerich is currently working on Jira 2.3 which will include this functionality and expect it to be released in the coming weeks.

**Comment by Snipa22** [comment] 2019-10-07 23:26
Apologies for the late delay, that looks like it would work perfectly for what I'm after!  Glad to have a migration plan from the old feed, love the plugin, it's made life much easier. :)

**Comment by levb** [comment] 2019-10-08 12:43
Closed as effectively a duplicate of the upcoming Jira 2.3

**Closed by levb** 2019-10-08 12:43 UTC
