### ISSUE TITLE
"Something went wrong" on /jira connect

### ISSUE THREAD

**Issue by rgarrigue** [mattermost/mattermost-plugin-jira#771] opened 2021-05-31 12:38 UTC
Hi there

I just installed and configured the plugin, trying to connect I got a Jira quite empty page, wit²h an error popup

> Something's gone wrong
> Our team has been notified. If the problem persists, please contact Atlassian Support.

JS console says stuff I don't understand

![image](https://user-images.githubusercontent.com/1872031/120193919-44db6080-c21d-11eb-83de-345c2340a25f.png)

I got no 4xx or 5xx on the network console, nothing on Mattermost's server logs. Tried to disable ublock & other stuff just in case, Firefox & Chromium... my colleagues got no luck either.

Is it broken actually ? Or can I enable more logs somehow ?

**Comment by mildbyte** [comment] 2021-07-28 10:06
Got the same issue on `/jira connect` (Mattermost 5.37.0, mattermost-plugin-jira 3.0.1) -- in my case, there was an error in the console:

![image](https://user-images.githubusercontent.com/828006/127304370-3932a975-0546-48f4-855f-7eeb61a2eba2.png)

Looks like Jira is trying to load MM's callback in an iframe and MM is sending the X-Frame-Options: SAMEORIGIN header? I worked around it by (temporarily! this is an actual security option) installing an addon to ignore it (https://addons.mozilla.org/en-GB/firefox/addon/ignore-x-frame-options-header/), at which point I was able to connect my account successfully.

**Comment by iamkhalidbashir** [comment] 2022-05-16 08:26
This is critical

**Comment by catalintomai** [comment] 2022-07-11 15:54
The forward path here is to implement OAuth 2.0 functionality. We do not have bandwidth at the time to address this particular flow.

**Comment by Nityanand13** [comment] 2022-09-12 10:25
I am not able to reproduce the error. So can you please share the steps to reproduce this error?

**Comment by Nityanand13** [comment] 2022-11-23 12:13
@rgarrigue @mildbyte  I am not getting any error in the console on `/jira connect` with (Mattermost 5.37.0, mattermost-plugin-jira 3.0.1). Can you please share the steps to reproduce this error?

**Comment by rgarrigue** [comment] 2022-11-28 23:19
Sorry, changed job, can't reproduce anymore

**Comment by Nityanand13** [comment] 2022-11-29 08:47
@catalintomai Are you able to reproduce this issue?

**Comment by raghavaggarwal2308** [comment] 2024-07-18 11:27
> The forward path here is to implement OAuth 2.0 functionality. We do not have bandwidth at the time to address this particular flow.

@mildbyte @catalintomai In the latest Jira release we are using oauth2 for jira cloud, I think that should solve the issue. Are you still facing the issue or we can close it?

**Closed** 2024-07-18 14:22 UTC
Labels: Type/Bug
