### ISSUE TITLE
Isolated case where instance is in the "list" key but its correct key is not found in the KV store

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#842] opened 2022-02-24 16:15 UTC
I have one isolated case where and instance ID is wrong and the instance cannot be uninstalled.  
![image](https://user-images.githubusercontent.com/35588783/155563108-3fec24f4-0f39-4319-bf38-bfd7c4739ffe.png)

As per Lev instance is in the "list" key, but its own key is not found in the KV store

I will attempt to find reproduction steps.

Observed Steps:
- Deployed latest Jira
- Run `/jira setup`
- Use Setup flow to install the intance
- Run `/jira list`

**Observed**: KV store shows an error and instance ID is wrong.

**Comment by catalintomai** [comment] 2022-02-28 20:05
@levb - could the growth spike -related changes introduce this? Dylan has the instance preserved if needed.

**Comment by levb** [comment] 2022-02-28 20:07
@catalintomai Yes, but it was likely the result of testing and failing. There are no specific steps to reproduce AFAIK.

**Comment by catalintomai** [comment] 2022-02-28 20:26
@dipak-demansol - can you help us identify repro steps?

**Comment by dipak-demansol** [comment] 2022-03-17 12:28
@DHaussermann i'm Not able to Regenerate the issue.

**Comment by Kshitij-Katiyar** [comment] 2023-03-06 07:17
@DHaussermann @hanzei @mickmister I am not able to reproduce this error. From the screenshots, it is looking like a Jira cloud instance so I tried installing that both using ```/jira setup``` and ```/jira instance install cloud <url>``` and both worked fine for me. I also tried your reproduction steps which also worked fine for me.
Just on a different note, this issue is looking similar to the issue https://github.com/mattermost/mattermost-plugin-jira/issues/902 for which I have created a PR https://github.com/mattermost/mattermost-plugin-jira/pull/914. Please see whether this PR solves this issue as well.

**Comment by raghavaggarwal2308** [comment] 2024-08-13 11:22
> @DHaussermann @hanzei @mickmister I am not able to reproduce this error. From the screenshots, it is looking like a Jira cloud instance so I tried installing that both using `/jira setup` and `/jira instance install cloud <url>` and both worked fine for me. I also tried your reproduction steps which also worked fine for me. Please let me know whether I should try this for jira server/datacenter as well. Just on a different note, this issue is looking similar to the issue #902 for which I have created a PR #914. Please see whether this PR solves this issue as well.

@DHaussermann @hanzei @dipak-demansol The PR #914 mentioned here was release in the [last Jira plugin release](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.1.1). Can you please confirm if the issue was fixed with that PR? If not, please let us know your opinions on this.

**Closed** 2024-09-18 09:16 UTC
Labels: Type/Bug
