### ISSUE TITLE
 Posts for Jira comments with line breaks show a quote but not all the text is indented

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#491] opened 2020-03-04 22:09 UTC
### Summary
Posts for Jira comments show a quote but not all the text is indented. When the text contains line breaks, additional lines of text are not intended. This look bad with the open quotes " as all comment text should be part of the quote.

![image](https://user-images.githubusercontent.com/7575921/75927524-21ffa800-5e32-11ea-8173-839cbbce1eac.png)

We should keep all the text indented with the quote symbol.

Steps: 

* Get  a DM from Jira that contains a Jira comment with line breaks in the text
* **Observed:** Only some of the text is indented. 
* **Expected:** If the quote symbol is there, all comment text should be indented.

### Additional Context

Connecting different paragraphs works by prefixing each line of text with `>`

![image](https://user-images.githubusercontent.com/7575921/75927613-51161980-5e32-11ea-9330-fc76ee11f871.png)

Even a naive algorithm like this:

![image](https://user-images.githubusercontent.com/7575921/75927631-5bd0ae80-5e32-11ea-8f13-7cc5d43a5130.png)

renders the same as this

![image](https://user-images.githubusercontent.com/7575921/75927653-6428e980-5e32-11ea-9025-a67f12bc7ea6.png)

### Ticket Link

https://mattermost.atlassian.net/browse/MM-19652

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by levb** [comment] 2020-05-29 12:25
I believe this is a dupe (subset) of https://github.com/mattermost/mattermost-plugin-jira/issues/148, no?

**Comment by mickmister** [comment] 2020-06-01 07:18
@levb Not really a dupe of that ticket. This is a quick win that delivers a lot of value imo

**Comment by aidapira** [comment] 2020-06-19 06:39
@mickmister Hi Michael, I have set up the environment and replicated it properly. I'm going to work on this issue.

**Comment by mickmister** [comment] 2020-06-19 06:40
Awesome, thanks @aidapira!

**Closed** 2020-07-29 20:58 UTC
Labels: Difficulty/1:Easy, Help Wanted, Tech/Go, Type/Enhancement
