### ISSUE TITLE
/jira subscribe displays help instead of subscription management

### ISSUE THREAD

**Issue by cadavre** [mattermost/mattermost-plugin-jira#384] opened 2019-11-14 17:58 UTC
I installed Jira app for Mattermost via `.json` file. When I try to `/jira subscribe` help shows up instead of integration popup. Other commands like `/jira view` works fine.

Plugin version: 2.2.2

**Comment by levb** [comment] 2019-11-27 16:57
@mickmister I just reproduced this on community after we deployed v2.3.0-rc1 there. The command works in the browser, but not in the desktop app (after a refresh). I am going to move the tracking of this ticket to Jira.

**Comment by levb** [comment] 2019-11-27 17:26
@cadavre @vertisan @greygoosey FWIW, when I quit and then re-started my Mattermost Desktop App, the command worked. This may be a workaround until we fix the root cause.

**Comment by vertisan** [comment] 2019-11-27 17:30
@levb I did this way:
1. Fully closed MM Desktop
2. Runned again
3. Switched to destination channel
4. Runned command `/jira subscribe`

But it show help instead of typical result of command.

Windows 10, Mattermost Desktop 4.3.0

**Comment by levb** [comment] 2019-12-03 00:47
tracking in https://mattermost.atlassian.net/browse/MM-20738

**Comment by mickmister** [comment] 2019-12-03 03:18
Hi @vertisan, I suggest the following to try and debug the issue:

- Try running `/jira create`. This is a client-side command just like `/jira subscribe`. If the command does not properly open the issue create modal, then the client-side portion in general is not working.

- Check the JS console to see if there is an error related to the plugin when refreshing the page, or when running `/jira subscribe`. The entire console output would be useful since it may not be obvious that a given error is involved with the plugin.

Thank you for your help!

**Comment by vertisan** [comment] 2019-12-03 09:01
Hi @mickmister , thanks for your response.
I have tried your tips but it's still does not work properly - I'm still getting help window. JS console is clear, I'm not getting any errors or warnings.
When I enter `/jira subscribe` command, `/api/v4/commands/execute` returns me:
```json
{
    "response_type":"",
    "text":"",
    "username":"",
    "channel_id":"",
    "icon_url":"",
    "type":"",
    "props":null,
    "goto_location":"",
    "trigger_id":"<I_hide_this_ID>",
    "attachments":null,
    "extra_responses":null
}
```

**Comment by mickmister** [comment] 2019-12-09 18:02
Hi @vertisan, I believe I have found the cause of your issue. Could you look in your Jira plugin settings in the admin console and see what the value for "Allow users to attach and create Jira issues in Mattermost" is?

It is currently tied to the subscriptions feature, and if set to false, the `/jira subscribe` command will be unavailable (it will print out the help text). This will be fixed in the upcoming release, so this config setting will not affect the subscriptions feature.

**Comment by jfrerich** [comment] 2020-01-28 01:55
The Jira ticket referenced in this issue has been closed and the relevant ticket to resolve this issue has been merged https://github.com/mattermost/mattermost-plugin-jira/pull/405

I am closing this ticket.  If the issue arises again, please reopen, or create another ticket.  Thanks to all for the issue submission and fix!

**Closed by jfrerich** 2020-01-28 01:55 UTC
Labels: Bug
