### ISSUE TITLE
Jira link tooltip: Content overflows off of the floating card

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#1018] opened 2024-01-10 19:36 UTC
![CleanShot 2024-01-10 at 14 35 58](https://github.com/mattermost/mattermost-plugin-jira/assets/6913320/8c9618e6-5a1d-4ec0-b9a6-e15a1a866201)

**Comment by yasserfaraazkhan** [comment] 2024-03-18 15:12
repoening. It was observed the text still overflow on server version 9.6
 https://mattermost.atlassian.net/browse/MM-57321

**Comment by mickmister** [comment] 2024-03-18 22:36
@raghavaggarwal2308 Can you please take a look at this? Thank you

**Comment by mickmister** [comment] 2024-03-18 23:38
@yasserfaraazkhan Are you able to provide the JSON response from the server here? You'll need to:

- Open browser dev tools. If you're using the desktop app, you can go to `View > Developer Tools for Current Server` to do this
- Go to the network tab
- Hover over the ticket with the issue
- Right-click the request in the network tab related to the tooltip
- Select "Copy response" in the right-click menu

Thanks

**Comment by yasserfaraazkhan** [comment] 2024-03-18 23:44
@mickmister , here it is.
 
 ```
 {
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_11138.properties,customfield_11108.requestTypePractice",
    "id": "",
    "self": "https://mattermost.atlassian.net/rest/api/2/issue/98392",
    "key": "MM-57315",
    "fields": {
        "Creator": {
            "Password": "",
            "active": true,
            "avatarUrls": {
                "16x16": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "24x24": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "32x32": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "48x48": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png"
            },
            "displayName": "Yasser Khan",
            "self": "",
            "timeZone": "America/Los_Angeles"
        },
        "aggregateprogress": {
            "percent": 0,
            "progress": 0,
            "total": 0
        },
        "assignee": {
            "Password": "",
            "accountId": "",
            "active": true,
            "avatarUrls": {
                "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/HS-6.png",
                "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/HS-6.png",
                "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/HS-6.png",
                "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/HS-6.png"
            },
            "displayName": "Harshil Sharma",
            "self": "https://mattermost.atlassian.net/rest/api/2/user?accountId=6054be09e394c30069d776ea",
            "timeZone": "America/Los_Angeles"
        },
        "attachment": [
            {
                "author": {
                    "Password": "",
                    "accountId": "",
                    "active": true,
                    "avatarUrls": {
                        "16x16": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                        "24x24": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                        "32x32": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                        "48x48": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png"
                    },
                    "displayName": "Yasser Khan",
                    "self": "",
                    "timeZone": "America/Los_Angeles"
                },
                "content": "https://mattermost.atlassian.net/rest/api/2/attachment/content/57915",
                "created": "",
                "filename": "image-20240318-100340.png",
                "id": "",
                "mimeType": "image/png",
                "self": "https://mattermost.atlassian.net/rest/api/2/attachment/57915",
                "size": 361947,
                "thumbnail": "https://mattermost.atlassian.net/rest/api/2/attachment/thumbnail/57915"
            }
        ],
        "comment": {
            "comments": []
        },
        "components": [],
        "created": "2024-03-18T03:04:31.22-0700",
        "creator": {
            "accountId": "62d18629a94a6f9c0eff460b",
            "accountType": "atlassian",
            "active": true,
            "avatarUrls": {
                "16x16": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "24x24": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "32x32": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "48x48": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png"
            },
            "displayName": "Yasser Khan",
            "self": "",
            "timeZone": "America/Los_Angeles"
        },
        "customfield_10000": null,
        "customfield_10001": null,
        "customfield_10003": null,
        "customfield_10004": null,
        "customfield_10006": "2|i04icv:",
        "customfield_10007": null,
        "customfield_10011": [
            {
                "boardId": 11,
                "endDate": "2024-03-18T03:44:45.000Z",
                "goal": "",
                "id": 536,
                "name": "Sprint 313 (March 12-March 18)",
                "startDate": "2024-03-12T16:06:52.292Z",
                "state": "active"
            }
        ],
        "customfield_10200": {
            "id": "10201",
            "self": "https://mattermost.atlassian.net/rest/api/2/customFieldOption/10201",
            "value": "S2_functionality_loss_or_glaring_UI_regressions"
        },
        "customfield_10500": null,
        "customfield_10600": {
            "hasEpicLinkFieldDependency": false,
            "nonEditableReason": {
                "message": "The Parent Link is only available to Jira Premium users.",
                "reason": "PLUGIN_LICENSE_ERROR"
            },
            "showField": false
        },
        "customfield_10700": "{}",
        "customfield_10800": null,
        "customfield_10900": null,
        "customfield_11100": null,
        "customfield_11101": {
            "id": "10785",
            "self": "https://mattermost.atlassian.net/rest/api/2/customFieldOption/10785",
            "value": "ICU"
        },
        "customfield_11103": null,
        "customfield_11104": null,
        "customfield_11105": null,
        "customfield_11106": null,
        "customfield_11107": null,
        "customfield_11108": null,
        "customfield_11109": [],
        "customfield_11110": null,
        "customfield_11111": null,
        "customfield_11112": null,
        "customfield_11113": null,
        "customfield_11114": null,
        "customfield_11116": null,
        "customfield_11117": null,
        "customfield_11118": "Fixed an issue where \u003cAdd Details\u003e. Thanks to \u003cReporter\u003e for contributing to this improvement under the Mattermost responsible disclosure policy.",
        "customfield_11119": null,
        "customfield_11121": null,
        "customfield_11123": null,
        "customfield_11124": null,
        "customfield_11125": null,
        "customfield_11126": null,
        "customfield_11127": null,
        "customfield_11129": null,
        "customfield_11130": null,
        "customfield_11131": null,
        "customfield_11133": "",
        "customfield_11134": 0,
        "customfield_11135": null,
        "customfield_11136": null,
        "customfield_11137": null,
        "customfield_11138": null,
        "customfield_11139": null,
        "customfield_11140": null,
        "customfield_11141": null,
        "customfield_11142": null,
        "customfield_11143": null,
        "customfield_11144": null,
        "customfield_11145": null,
        "customfield_11146": null,
        "customfield_11147": null,
        "customfield_11148": null,
        "customfield_11149": null,
        "customfield_11150": null,
        "customfield_11151": null,
        "customfield_11152": null,
        "customfield_11153": null,
        "customfield_11155": null,
        "customfield_11156": null,
        "customfield_11157": null,
        "customfield_11158": null,
        "customfield_11159": null,
        "customfield_11160": null,
        "customfield_11161": null,
        "customfield_11162": null,
        "customfield_11163": null,
        "customfield_11164": null,
        "customfield_11165": null,
        "customfield_11166": null,
        "customfield_11167": null,
        "customfield_11168": null,
        "customfield_11169": null,
        "customfield_11170": null,
        "customfield_11171": null,
        "customfield_11172": null,
        "customfield_11173": null,
        "customfield_11174": null,
        "customfield_11175": null,
        "customfield_11176": null,
        "customfield_11177": null,
        "customfield_11178": null,
        "customfield_11179": null,
        "customfield_11180": null,
        "customfield_11181": null,
        "customfield_11182": null,
        "customfield_11183": null,
        "customfield_11184": null,
        "customfield_11185": null,
        "customfield_11186": null,
        "customfield_11187": null,
        "customfield_11188": null,
        "customfield_11189": null,
        "customfield_11190": [],
        "customfield_11193": null,
        "customfield_11194": null,
        "customfield_11195": null,
        "customfield_11196": null,
        "customfield_11197": null,
        "customfield_11198": null,
        "customfield_11199": null,
        "customfield_11202": null,
        "customfield_11203": null,
        "customfield_11204": null,
        "customfield_11205": null,
        "customfield_11206": null,
        "customfield_11207": null,
        "customfield_11208": null,
        "customfield_11209": null,
        "customfield_11210": null,
        "customfield_11211": null,
        "customfield_11212": null,
        "customfield_11213": null,
        "customfield_11214": null,
        "customfield_11215": null,
        "customfield_11216": null,
        "customfield_11217": null,
        "customfield_11218": null,
        "customfield_11219": null,
        "customfield_11220": null,
        "customfield_11221": null,
        "customfield_11222": null,
        "customfield_11223": null,
        "customfield_11224": null,
        "customfield_11226": null,
        "customfield_11227": null,
        "customfield_11229": null,
        "customfield_11231": null,
        "customfield_11233": null,
        "customfield_11235": null,
        "description": "also Fix e2e test : \n\n* [https://github.com/mattermost/mattermost/blob/a9a879d00d244236a9347fc6bd5bcea72dbd96a6/e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_1_spec.ts|https://github.com/mattermost/mattermost/blob/a9a879d00d244236a9347fc6bd5bcea72dbd96a6/e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_1_spec.ts|smart-link]  \n* [https://github.com/mattermost/mattermost/blob/a9a879d00d244236a9347fc6bd5bcea72dbd96a6/e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_2_spec.ts|https://github.com/mattermost/mattermost/blob/a9a879d00d244236a9347fc6bd5bcea72dbd96a6/e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_2_spec.ts|smart-link] \n* [https://github.com/mattermost/mattermost/blob/a9a879d00d244236a9347fc6bd5bcea72dbd96a6/e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_3_spec.ts|https://github.com/mattermost/mattermost/blob/a9a879d00d244236a9347fc6bd5bcea72dbd96a6/e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_3_spec.ts|smart-link] \n* [https://github.com/mattermost/mattermost/blob/f1f54508f414275226409691aa8a690889a723cb/e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_1_spec.ts|https://github.com/mattermost/mattermost/blob/f1f54508f414275226409691aa8a690889a723cb/e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_1_spec.ts|smart-link]  \n\n!image-20240318-100340.png|width=1370,height=858!\n\n\n",
        "fixVersions": [
            {
                "archived": false,
                "id": "12804",
                "name": "v9.7 (April 2024)",
                "releaseDate": "2024-04-16",
                "released": false,
                "self": "https://mattermost.atlassian.net/rest/api/2/version/12804"
            }
        ],
        "issuelinks": [],
        "issuerestriction": {
            "issuerestrictions": {},
            "shouldDisplay": false
        },
        "issuetype": {
            "avatarId": 10303,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://mattermost.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium",
            "id": "1",
            "name": "Bug",
            "self": "https://mattermost.atlassian.net/rest/api/2/issuetype/1"
        },
        "labels": [],
        "lastViewed": "2024-03-18T03:06:09.272-0700",
        "progress": {
            "percent": 0,
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://mattermost.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12528?size=xsmall",
                "24x24": "https://mattermost.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12528?size=small",
                "32x32": "https://mattermost.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12528?size=medium",
                "48x48": "https://mattermost.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/12528"
            },
            "id": "10302",
            "key": "MM",
            "name": "Mattermost",
            "self": "https://mattermost.atlassian.net/rest/api/2/project/10302"
        },
        "reporter": {
            "Password": "",
            "accountId": "",
            "active": true,
            "avatarUrls": {
                "16x16": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "24x24": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "32x32": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png",
                "48x48": "https://secure.gravatar.com/avatar/12e1a72edb468ff4c41241ae2cb31f91?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FYK-1.png"
            },
            "displayName": "Yasser Khan",
            "self": "",
            "timeZone": "America/Los_Angeles"
        },
        "security": null,
        "status": {
            "description": "The issue is open and ready for the assignee to start work on it.",
            "iconUrl": "https://mattermost.atlassian.net/images/icons/statuses/open.png",
            "id": "1",
            "name": "Open",
            "self": "https://mattermost.atlassian.net/rest/api/2/status/1",
            "statusCategory": {
                "colorName": "blue-gray",
                "id": 2,
                "key": "new",
                "name": "To Do",
                "self": "https://mattermost.atlassian.net/rest/api/2/statuscategory/2"
            }
        },
        "statuscategorychangedate": "2024-03-18T03:04:32.149-0700",
        "subtasks": [],
        "summary": "Custom Emoji | Annimated gif | Uploading a annimated gif as emoji is failing with error `http: request body too large`",
        "timetracking": {},
        "updated": "2024-03-18T11:37:57.58-0700",
        "votes": {
            "hasVoted": false,
            "self": "https://mattermost.atlassian.net/rest/api/2/issue/MM-57315/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": true,
            "self": "https://mattermost.atlassian.net/rest/api/2/issue/MM-57315/watchers",
            "watchCount": 2
        },
        "worklog": {
            "maxResults": 20,
            "startAt": 0,
            "total": 0,
            "worklogs": []
        },
        "workratio": -1
    }
}
 ```

**Comment by raghavaggarwal2308** [comment] 2024-03-19 13:40
@mickmister @yasserfaraazkhan I tried reproducing the issue with the latest release i.e. v4.1.0 but it was not reproducible on my end. I tested it on mm cloud server version v9.4.0 and v9.6.0, 
Can you please confirm if the user facing the issue is using the latest release and try clearing the browser cache maybe?

On cloud server v9.6.0
![image](https://github.com/mattermost/mattermost-plugin-jira/assets/55234496/f88077b6-13e8-4036-99db-30986b718c33)

**Comment by yasserfaraazkhan** [comment] 2024-03-19 13:45
@raghavaggarwal2308 @mickmister .
can you try creating a Bug/task , in open state and check?
I see in the screenshot you shared there double square brackets `[[https` . Not sure if this makes any difference, but you can try to rerproduce.

its seen on community server.
<img width="786" alt="Screenshot 2024-03-19 at 7 11 57 PM" src="https://github.com/mattermost/mattermost-plugin-jira/assets/15979783/8799be09-6770-40a8-8aed-ecf4599eb0ab">
<img width="805" alt="Screenshot 2024-03-19 at 7 12 01 PM" src="https://github.com/mattermost/mattermost-plugin-jira/assets/15979783/48f6383c-8b18-44c9-a0bb-0e0ed33b0d9d">

<img width="557" alt="Screenshot 2024-03-19 at 7 11 42 PM" src="https://github.com/mattermost/mattermost-plugin-jira/assets/15979783/3aa58c88-98a3-4f6b-8711-37a97200be8c">

<img width="233" alt="Screenshot 2024-03-19 at 7 11 15 PM" src="https://github.com/mattermost/mattermost-plugin-jira/assets/15979783/09a291a1-0986-41fd-a0e1-3839a0aaac1b">

**Comment by yasserfaraazkhan** [comment] 2024-03-20 03:34
@raghavaggarwal2308 
another text overflow seen in community.
<img width="894" alt="image" src="https://github.com/mattermost/mattermost-plugin-jira/assets/15979783/dcd3475f-edc8-4165-88bf-4a97e5bdf944">

**Comment by ayusht2810** [comment] 2024-03-20 09:16
@yasserfaraazkhan Can you please try once again after looking at this [comment](https://github.com/mattermost/mattermost-plugin-jira/issues/1018#issuecomment-2007209054).
cc: @mickmister

**Comment by yasserfaraazkhan** [comment] 2024-03-20 10:50
> @yasserfaraazkhan Can you please try once again after looking at this [comment](https://github.com/mattermost/mattermost-plugin-jira/issues/1018#issuecomment-2007209054). cc: @mickmister

https://github.com/mattermost/mattermost-plugin-jira/issues/1018#issuecomment-2008612838
@raghavaggarwal2308  @ayusht2810 I did try again in the above comment.
I'm using desktop 5.7 version of Mac

**Comment by mickmister** [comment] 2024-03-20 18:11
FYI community is currently running:

Jira version: 4.1.0, [c52dea3](https://github.com/mattermost/mattermost-plugin-jira/commit/c52dea3eab04f94ddbf82bb3a18b40297a274e47)

**Comment by ayusht2810** [comment] 2024-03-26 14:20
@yasserfaraazkhan @mickmister the issue is reproducible on Jira `v4.1.0-rc3`. But it is fixed in Jira `v4.1.0`. I think we may need to update the version present in the community.

**Comment by yasserfaraazkhan** [comment] 2024-03-26 14:23
> @yasserfaraazkhan @mickmister the issue is reproducible on Jira `v4.1.0-rc3`. But it is fixed in Jira `v4.1.0`. I think we may need to update the version present in the community.

oh!! Great work in finding it!!

I'll let @amyblais and @mickmister look into this, and close this issue once its updated.

**Comment by mickmister** [comment] 2024-03-27 16:43
@ayusht2810 @yasserfaraazkhan The plugin was updated on community to `4.1.1-rc1` on community today, which contains the changes of `4.1.0`. I think `hub` also needs to be updated

**Comment by Kshitij-Katiyar** [comment] 2024-05-13 10:07
@mickmister Is this fixed on community now, if it is fixed we can close the issue ?

**Closed** 2024-05-14 15:05 UTC
Labels: Type/Bug
