### ISSUE TITLE
Add an ephemeral response after user completes "/jira connect" flow

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#149] opened 2019-06-09 03:07 UTC
**Repro steps**:
1. Enable and configure the plugin using steps at https://github.com/mattermost/mattermost-plugin-jira
2. Use "/jira connect" to connect your Mattermost account with Jira
3. Complete the connection flow

**Observed**: No feedback sent back in Mattermost after completing the flow.

**Proposed changes**:

1) If the user successfully connects their account: Ephemeral message posted to user with text
```
You have successfully connected your Jira account (**{Jira email address}**).
```

2) If the connection is not successful: Ephemeral message posted to user with text
```
We were not able to connect your Jira account. Please try again later.
```

3) If the user had already connected their account: Ephemeral message posted to user with text
```
You already have a Jira account (**{Jira email address}**) connected. If you would like to connect another account, use `/jira disconnect` to first disconnect the existing one.
```
----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by levb** [comment] 2020-01-21 15:24
@jfrerich is there someone who is working on this issue now? Can you please comment with the github username?

**Comment by AGMETEOR** [comment] 2020-02-06 10:44
@jfrerich looks like part of this was already implemented. Currently, when I run `/jira connect` I get `You already have a Jira account linked to your Mattermost account. Please use /jira disconnect to disconnect.` I'll investigate this further.

**Comment by levb** [comment] 2020-02-06 15:29
@AGMETEOR I _think_ the ask is that the user gets both a DM and an ephemeral message in their current context; I'm 0/5 if it's a good idea/best practice indeed. @aaronrothschild @asaadmahmood can you please clarify?

**Comment by jfrerich** [comment] 2020-02-06 16:12
@AGMETEOR, You are correct and I believe bullet #3 is also implemented.  I haven't verified bullet #2.  It is possible this is already implemented.  Let's wait a bit to hear back from PM and UX.

**Comment by aaronrothschild** [comment] 2020-02-13 12:22
> @AGMETEOR, You are correct and I believe bullet #3 is also implemented. I haven't verified bullet #2. It is possible this is already implemented. Let's wait a bit to hear back from PM and UX.

@jfrerich @AGMETEOR  I think we should add a DM from the Jira bot that says "Thanks for connecting your account {EMAIL_ADDRESS}, you can get started by typing `/jira` in your chat window" so the user knows what to do next.  The ephemeral message will be displayed wherever they are, but disappears on next reload of their client.  The Jira DM draws attention and directs the user what to do next IMO. 

For #2, how long would we wait before we throw an error?

**Comment by levb** [comment] 2020-05-13 13:05
Adding ephemeral messages would need to be done around https://github.com/mattermost/mattermost-plugin-jira/blob/09711c0b034f9ce41568fe413f8f3b3d747e3c09/server/user_cloud.go#L110. One issue to solve is the missing channelID, needs to be added to `mmToken` at its origination, in https://github.com/mattermost/mattermost-plugin-jira/blob/09711c0b034f9ce41568fe413f8f3b3d747e3c09/server/instance.go#L28 and all of its callers (including the webapp?)

**Comment by promulo** [comment] 2020-10-09 14:24
Hello, is this issue ready to be worked on?

**Comment by jasonblais** [comment] 2020-10-09 14:33
cc @aaronrothschild @levb on above question

> Hello, is this issue ready to be worked on?

**Comment by aaronrothschild** [comment] 2020-10-09 14:49
@promulo I think it's ready to be worked on... any questions?

**Comment by promulo** [comment] 2020-10-09 14:54
@aaronrothschild no questions yet, just checking if you're expecting any other input from other maintainers. I would like to give it a try if nobody else is working on it. :)

**Comment by aaronrothschild** [comment] 2020-10-09 14:55
@promulo Awesome, give it a shot - I'll assign to you so no one else takes it up.  Thansk for contributing, let me @levb or @jfrerich if you have any questions or concerns!  Happy friday!

**Comment by promulo** [comment] 2020-10-09 14:59
Perfect, thanks!

**Comment by promulo** [comment] 2020-10-22 13:01
Hi @aaronrothschild, I have a question about what's expected here. The issue description mentions "ephemeral message posted to user", which I assumed where not DMs but messages on the channel the user is currently in. However, you mention in a comment that the user should get a DM instead. What are the requirements here? The current behavior seems to be the ephemeral message approach for the unsuccessful connection cases, are those supposed to become DMs as well? Thanks for clarifying.

**Comment by aaronrothschild** [comment] 2020-10-22 16:49
> Hi @aaronrothschild, I have a question about what's expected here. The issue description mentions "ephemeral message posted to user", which I assumed where not DMs but messages on the channel the user is currently in. However, you mention in a comment that the user should get a DM instead. What are the requirements here? The current behavior seems to be the ephemeral message approach for the unsuccessful connection cases, are those supposed to become DMs as well? Thanks for clarifying.

On success - I think we should send: 
- A DM from the JiraBot.  This message will persist in the DM so the user can go back and recall to type `/jira`
- and an ephemeral message in whatever channel they are currently on (likely in the channel where they just clicked the "connect URL" to go to the oauth flow).  This will disappear after refresh and the user could forget how they invoke `/jira`.  

On Failure, we should do the same.  

cc @abhijit-singh any thoughts on this behavior?

**Comment by abhijit-singh** [comment] 2020-10-22 17:51
@aaronrothschild I'm not sure if we should send a DM from the JiraBot in case of failure. Won't the user likely take the follow up action right there & then? But I'm 1/5 here.

Also, on success, the DM from JiraBot could also convey that 'this is where they'll get their personal notifications for mentions and issues assigned in Jira', - As per [Personal Notifications: JiraBot](https://mattermost.gitbook.io/plugin-jira/feature-summary#personal-notifications-jirabot)

**Comment by aaronrothschild** [comment] 2020-10-22 18:06
> @aaronrothschild I'm not sure if we should send a DM from the JiraBot in case of failure. Won't the user likely take the follow up action right there & then? But I'm 1/5 here.

Good point, i think you're right.  No DM's for failure. 

> Also, on success, the DM from JiraBot could also convey that 'this is where they'll get their personal notifications for mentions and issues assigned in Jira', - As per [Personal Notifications: JiraBot](https://mattermost.gitbook.io/plugin-jira/feature-summary#personal-notifications-jirabot) 

Great idea, can you suggest the specific text we should insert so @promulo can use it?  thanks!

**Comment by abhijit-singh** [comment] 2020-10-23 09:59
The DM from JiraBot could say - "Thanks for connecting your account {EMAIL_ADDRESS}, you can get started by typing /jira in your chat window. You'll get a post here whenever someone mentions you or assigns an issue to you in Jira."

cc @aaronrothschild

**Comment by promulo** [comment] 2020-10-27 01:48
Hi, @aaronrothschild. I might have reached a kind of crossroad here. It seems things have changed since this issue was created. Please bear with me while I try to explain.

So, after some digging and testing, it seems that the handling of `/jira connect` happens in a different way than most of the other commands, including its counterpart `/jira disconnect`. Basically, it is all handled by the plugin webapp and not by the server. The reason for that is probably the OAuth flow. I'm not really well-versed in Typescript (or frontend in general), but from what I can see all the connect logic resides here, at least for cloud: https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/actions/index.ts#L354. You can see that the even the ephemeral messages coming from the connect flow are different. They come from "System" instead of the "jira" bot.

The webapp seems to "intercept" the `/jira connect` command and redirect the flow to happen within the Typescript layer. Maybe the Go code is used only by the server flow? I could not test it with a server installation. The `disconnect`, on the other hand, is surely forwarded to the server, as it can be seen here: https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/hooks/hooks.ts#L116.

It is possible to send an ephemeral message after the connect flow is done (see #711), but I couldn't see a way to easily retrieve the user e-mail. Also, I'm not sure how the DMs are handled from the webapp, if possible at all.

With all that being said, I'm not sure how to proceed. Some direction would be appreciated but it might be the case that you guys want to discuss this internally as this might be the case of a substantial rewrite.

**Comment by promulo** [comment] 2020-10-27 09:45
I forgot to mention one thing. I checked if the webapp generated a custom webhook to the server but it does not seem the case. If it's possible to somehow generate a `custom_jira_connect` event/webhook from the plugin webapp and handle it server-side, that could be one way to go.

**Comment by aaronrothschild** [comment] 2020-10-27 14:08
> With all that said, I'm not quite sure how to proceed. Some direction would be appreciated but it might be the case that you guys want to discuss this internally as this might be the case of a substantial rewrite (or not :).

@promulo I'm not a developer, but I can see what you're saying happening.  I'm so sorry for the confusion here, going back - I can see this is an old issue and you're right - thing have likely changed quite a bit since then!   Sorry for not realizing earlier!

**Comment by promulo** [comment] 2020-10-27 15:08
@aaronrothschild all good. Happy to give a bit more context if necessary, either here or on the plugin MM room. :)

**Comment by aaronrothschild** [comment] 2020-10-28 14:09
@mickmister Any thoughts on this issue?

**Comment by mickmister** [comment] 2020-11-02 21:33
@promulo Since the connect process is handled client-side, then the posts can be made client-side. It is okay if it says `System` posted the message. There's an open ticket for that https://github.com/mattermost/mattermost-plugin-jira/issues/560 .

I believe there is also a server-handled portion for when the command is run on the mobile app. So the post would also need to be created for that case. This will likely make things more complicated though.

@promulo What are your thoughts on this? Does there seem to be a central place for this logic to go? IIRC the server is unaware of when the user has finished their OAuth process, and we can't any custom plugin functionality into the mobile app. This may only be supported in the context of connecting from the browser.

**Comment by promulo** [comment] 2020-11-08 12:43
Hi @mickmister, thanks for the input. From what I could verify, the server-side `[executeConnect](https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/command.go#L410)` is never reached during the OAuth flow for Jira cloud. It may be the case that that code is executed for on-prem Jira but I could not test this case.

One thing I wanted to try was to leverage the server's webhook handling logic and somehow generate a `custom_jira_connect` webhook from the client. That could make it easier to send the DM from the Jira bot to the user. However, my TypeScript skills are rather limited and I'm not sure if that is possible at all.

Does that make sense?

**Comment by mickmister** [comment] 2020-11-10 08:41
@promulo 
If the client is aware that an ephemeral message needs to be posted, then I recommend just creating it client-side and not worry about getting the server involved. There should be a `sendEphemeralPost` function being used throughout the webapp side of the plugin. It is okay that the message will say `System`. Does this make sense? I may be missing something else here with the complications of the code.

**Comment by promulo** [comment] 2020-11-10 09:10
Hi @mickmister, that was already done by #711 . The problem is that the issue requirements (check above comments by @aaronrothschild and @abhijit-singh) also include a DM from the Jira bot and displaying the user e-mail in the ephemeral message. Those requirements I'm not sure can be handled by the client.

**Comment by mickmister** [comment] 2020-11-10 09:14
@promulo Understood. I think sending a ping to the server saying the user is connected is the right thing to do then, as you suggested. The websocket events are mainly meant for `server -> client` communication, so I suggest using the API to communicate to the server instead of creating a new websocket event. Maybe a `user-has-connected` endpoint?

**Comment by promulo** [comment] 2020-11-10 09:18
Thanks @mickmister, that sounds good to me. I'll have a look and see what I can come up with.

**Comment by promulo** [comment] 2020-11-10 09:20
Should that maybe be done in a separate PR? 🤔 So by merging #711 we'd have at least something the user can see in the meantime.

**Comment by mickmister** [comment] 2020-11-10 09:28
@promulo Sounds good to me :+1:

**Closed** 2020-11-20 02:37 UTC
Labels: Difficulty/2:Medium, Good First Issue, Hacktoberfest, Help Wanted, Tech/Go, Type/Enhancement
