### ISSUE TITLE
Plugin 1.1.0 not working anymore.

### ISSUE THREAD

**Issue by kix23** [mattermost/mattermost-plugin-jira#20] opened 2019-02-05 11:31 UTC
We are runing Mattermost on an Ubuntu 16.04.
Since update MM to 5.7.1 yesterday the Jira Plugin stopped working.
Activation of Plugin is successful (it says)
In Jira we didn't change the hook.
https://mattermost.ourserver.lan/plugins/jira/webhook?secret=xxxx&team=ourteam&channel=jiranotes
If i open the link in a Browser it gives me "500 internal server error"
If Jira hits it, I get following in the logs:
```
2019-02-05T10:22:56.324Z	error	plugin/client_rpc.go:326	Plugin failed to ServeHTTP, RPC call failed	{"plugin_id": "jira", "error": "connection is shut down"}
2019-02-05T10:23:01.324Z	error	plugin/client_rpc.go:281	Plugin failed to ServeHTTP, muxBroker couldn't accept connection	{"plugin_id": "jira", "serve_http_stream_id": 22, "error": "timeout waiting for accept"}
2019-02-05T10:23:01.324Z	error	plugin/client_rpc.go:300	Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection	{"plugin_id": "jira", "error": "timeout waiting for accept"}
```
config show gives me the values, which are set in the config.json:
`jira:map[username:jira-bot enabled:true secret:xxx]`

If i try to change settings (enable/disable or username) in the webinterface following appears in the logs:
`2019-02-05T11:01:45.346Z	error	plugin/client_rpc_generated.go:67	RPC call OnConfigurationChange to plugin failed.	{"plugin_id": "jira", "error": "connection is shut down"}`

Settings in the plugin.json seem ok (relative path to plugin path not changed).
```
{
    "id": "jira",
    "name": "Jira",
    "description": "Receives webhook events from JIRA and makes Mattermost posts for them.",
    "version": "1.1.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
...
```
Btw: other plugins like autolink are working fine.

**Comment by hanzei** [comment] 2019-02-05 15:33
Hey @kix23,

Thanks for the report. Could you set the server log level to `debug` and see if there any other log messages related to the JIRA plugin? If you don't want to share you logs public, you can DM me them on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by ChrisBridson** [comment] 2019-02-08 15:50
Similarly:
```
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.0841444,"caller":"go-plugin/client.go:537","msg":"starting plugin","plugin_id":"jira","wrapped_extras":"path/opt/mattermost/plugins/jira/server/dist/plugin-linux-amd64args[/opt/mattermost/plugins/jira/server/dist/plugin-linux-amd64]"}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.0850143,"caller":"go-plugin/client.go:621","msg":"waiting for RPC address","plugin_id":"jira","wrapped_extras":"path/opt/mattermost/plugins/jira/server/dist/plugin-linux-amd64"}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.0956252,"caller":"go-plugin/client.go:832","msg":"plugin address","plugin_id":"jira","wrapped_extras":"address/tmp/plugin209106673networkunixtimestamp2019-02-08T15:44:16.095Z"}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.0956628,"caller":"go-plugin/client.go:669","msg":"using plugin","plugin_id":"jira","wrapped_extras":"version1"}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.1023653,"caller":"jobs/workers.go:104","msg":"Workers received config change."}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.1023989,"caller":"jobs/schedulers.go:185","msg":"Schedulers received config change."}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.114996,"caller":"jobs/schedulers.go:167","msg":"Next run time for scheduler MigrationsScheduler: 2019-02-08 15:45:16.114960886 +0000 GMT m=+105.004145739"}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.1354067,"caller":"jobs/workers.go:104","msg":"Workers received config change."}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.1354887,"caller":"jobs/schedulers.go:185","msg":"Schedulers received config change."}
Feb  8 15:44:16 v0950 mattermost: {"level":"debug","ts":1549640656.1385758,"caller":"jobs/schedulers.go:167","msg":"Next run time for scheduler MigrationsScheduler: 2019-02-08 15:45:16.138551889 +0000 GMT m=+105.027736701"}
...
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5096567,"caller":"app/plugin_api.go:624","msg":"HTTP request","plugin_id":"jira","Host":"XXXXXXXXXXXXXXX","RequestURI":"/plugins/jira/webhook?secret=XXXXXXXXXXXXXXX&team=XXXXXXXXXXXXXXX&channel=town-square&user_id=XXXXXXXXXXXXXXX&user_key=XXXXXXXXXXXXXXX","Method":"POST","query":"channel=town-square&secret=XXXXXXXXXXXXXXX&team=XXXXXXXXXXXXXXX&user_id=XXXXXXXXXXXXXXX&user_key=XXXXXXXXXXXXXXX"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5118139,"caller":"app/plugin_api.go:624","msg":"Failed to serve HTTP request","plugin_id":"jira","Error message":"Failed to create post"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5213375,"caller":"go-plugin/client.go:823","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5213733,"caller":"go-plugin/client.go:823","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x933af2]","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.521388,"caller":"go-plugin/client.go:823","msg":"","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5214045,"caller":"go-plugin/client.go:823","msg":"goroutine 25 [running]:","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5214295,"caller":"go-plugin/client.go:823","msg":"github.com/mattermost/plugin-jira/server/vendor/github.com/mattermost/mattermost-server/model.ParseSlackAttachment(0xc000348120, 0xc0001588d0, 0x1, 0x1)","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5214477,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/go/src/github.com/mattermost/plugin-jira/server/vendor/github.com/mattermost/mattermost-server/model/slack_attachment.go:72 +0x172","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5214617,"caller":"go-plugin/client.go:823","msg":"main.(*Plugin).ServeHTTP(0xc0002047e0, 0xc000156ef0, 0xc63a20, 0xc000156f70, 0xc000310000)","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5214756,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/go/src/github.com/mattermost/plugin-jira/server/plugin.go:118 +0x931","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.521491,"caller":"go-plugin/client.go:823","msg":"github.com/mattermost/plugin-jira/server/vendor/github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ServeHTTP(0xc0002745c0, 0xc000154260, 0x11a5fe8, 0x0, 0x0)","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5215063,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/go/src/github.com/mattermost/plugin-jira/server/vendor/github.com/mattermost/mattermost-server/plugin/client_rpc.go:356 +0x254","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5215373,"caller":"go-plugin/client.go:823","msg":"reflect.Value.call(0xc00026cde0, 0xc0002803f8, 0x13, 0xb864d7, 0x4, 0xc00004df18, 0x3, 0x3, 0xc00015c280, 0x0, ...)","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5215542,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/.local/go/src/reflect/value.go:447 +0x454","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5215688,"caller":"go-plugin/client.go:823","msg":"reflect.Value.Call(0xc00026cde0, 0xc0002803f8, 0x13, 0xc000289f18, 0x3, 0x3, 0x0, 0xc0001505a0, 0x0)","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.521582,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/.local/go/src/reflect/value.go:308 +0xa4","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.521596,"caller":"go-plugin/client.go:823","msg":"net/rpc.(*service).call(0xc000258800, 0xc00027e190, 0xc00025a478, 0xc00025a4a0, 0xc0002ac780, 0xc0002750c0, 0xa44960, 0xc000154260, 0x16, 0xa541e0, ...)","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5216112,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/.local/go/src/net/rpc/server.go:384 +0x14e","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5216253,"caller":"go-plugin/client.go:823","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5216389,"caller":"go-plugin/client.go:823","msg":"\t/home/bschumacher/.local/go/src/net/rpc/server.go:481 +0x47e","plugin_id":"jira"}
Feb  8 15:44:38 v0950 mattermost: {"level":"error","ts":1549640678.522289,"caller":"plugin/client_rpc.go:326","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"jira","error":"unexpected EOF"}
Feb  8 15:44:38 v0950 mattermost: {"level":"debug","ts":1549640678.5223033,"caller":"go-plugin/client.go:571","msg":"plugin process exited","plugin_id":"jira","wrapped_extras":"path/opt/mattermost/plugins/jira/server/dist/plugin-linux-amd64"}
```

**Comment by dcherniv** [comment] 2019-02-16 03:33
I can reproduce as well, on mattermost 5.8 team edition:
```
{"level":"debug","ts":1550287816.6157136,"caller":"app/plugin_api.go:650","msg":"HTTP request","plugin_id":"jira","Host":"REDACTED","RequestURI":"/plugins/jira/webhook?secret=REDACTED&team=devops&channel=devops-notify&user_id=REDACTED&user_key=REDACTED","Method":"POST","query":"channel=devops-notify&secret=REDACTED&team=devops&user_id=REDACTED&user_key=REDACTED"}
{"level":"debug","ts":1550287816.6180508,"caller":"app/plugin_api.go:650","msg":"Failed to serve HTTP request","plugin_id":"jira","Error message":"Failed to create post"}
```

**Comment by kix23** [comment] 2019-02-18 10:34
Works again here after Mattermost update to 5.8.0.

**Comment by Simiil** [comment] 2019-02-19 14:43
same here, with mattermost 5.8.0

**Comment by Simiil** [comment] 2019-02-21 18:12
Why was this closed? what i meant is that i have this bug as well, and i'm on version 5.8.0

**Comment by hanzei** [comment] 2019-02-21 19:59
Hey @Simiil,

Could you please:
1. Update to [v1.1.1](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v1.1.1)
2. Post your server logs related to this issue

This would help debugging this.

**Comment by Simiil** [comment] 2019-02-22 10:44
current version of the jira plugin is already 1.1.1

the mattermost logs:

    {"level":"debug","ts":1550830591.4017985,"caller":"app/plugin_api.go:650","msg":"HTTP request","plugin_id":"jira","Host":"my-hostname","RequestURI":"/plugins/jira/webhook?secret=correct-secret&team=correct-team&channel=correct-channel&user_id=user&user_key=user","Method":"POST","query":"channel=correct-channel&secret=correct-secret&team=correct-team&user_id=user&user_key=user"}
    {"level":"debug","ts":1550830591.4024615,"caller":"app/plugin_api.go:650","msg":"Failed to serve HTTP request","plugin_id":"jira","Error message":"Failed to create post"}


jiras logs:

     2019-02-22 05:16:30,841 httpclient-callbacks:thread-1 WARN anonymous     [c.a.webhooks.plugin.PublishTaskFactoryImpl$PublishTaskImpl] Server error - 500 when posting to web hook at 'https://host/plugins/jira/webhook?secret=correct_secret&team=correct_team&channel=correct_channel'

I can reproduce the error by posting the json directly to the webhook endpoint.
The json basically looks like:

    {
        "timestamp": 1550772231746,
        "webhookEvent": "jira:issue_updated",
        "issue_event_type_name": "issue_comment_deleted",
        "user": {...}
        "issue": {...}
    }

the `user` and `issue`  field contain large amounts of data, but it seems to be correct.

An additional thing i notice is that i resolved a task in jira, and this was correctly posted to mattermost. i dont have the corresponding json for that event though.

**Comment by hanzei** [comment] 2019-02-22 11:15
Thanks for posting your logs.

The event triggered is currently not supported by this plugin. The supported types at the moment are:
- issue_created
- issue_updated
- issue_deleted

Because of this you don't see a message in Mattermost. We are currently working on supporting more event types. See https://github.com/mattermost/mattermost-plugin-jira/pull/22 for the progress.

**Comment by Simiil** [comment] 2019-02-22 13:26
I see, now that you mentioned it i found it in the documentation too.
the supported types work.

**Comment by hanzei** [comment] 2019-02-22 13:39
Closing this one for now. Please report back, when you see the issue with some of the supported types.

**Closed by hanzei** 2019-02-22 13:39 UTC
