### ISSUE TITLE
UI will allow user to attempt to create a subscription if they have Create permission but not Browse

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#496] opened 2020-03-08 20:48 UTC
It was previously established that creating a subscription for a project would require both "Browse Project" and "Create Project" This is the correct functionality.

The Bug is that If users have Create but not Browse (definitely an edge case), the project still shown in the drop down and they can attempt to make a subscription. On save they will see `modification error: failed to get project "<nane>": - No project could be found with key '<name>'.`

Since the save is not possible, the project should be hidden from the drop down.

**Comment by Kshitij-Katiyar** [comment] 2024-09-05 04:14
@wiggin77 @DHaussermann
I investigated this issue and here are my findings:
- The `No project could be found with key '<name>'` error is reproducible if a user had "Browse" permission in a project, created an issue using `/jira issue create`, and then lost the permission. When the user runs `/jira issue create`, the project without permission is preselected in the dropdown, causing the error in the modal header.
  ![Screenshot from 2024-09-04 16-43-24](https://github.com/user-attachments/assets/a675cb98-5b9b-45f8-bd37-dd85b96f93cf)
- A similar error occurs if no project is preselected, the user selects a project where they lack "Browse" permission, and attempts to create an issue. 
  ![Screenshot from 2024-09-04 17-06-39](https://github.com/user-attachments/assets/316a088d-88ce-4228-8530-d6f346471d34)
- The `getProject` API incorrectly returns projects where the user has any permission, contrary to the Jira API documentation, which states it should only return projects where "Browse" permission exists.
  ![Screenshot from 2024-09-04 13-41-37](https://github.com/user-attachments/assets/6f5cbd43-80d0-43b5-be42-ec3a93e982c9)
- The current API cannot be modified to retrieve exact permissions in the project. A workaround is making additional API calls to check user permissions across all projects, but this is resource-intensive.

**Comment by DHaussermann** [comment] 2024-09-06 14:45
Thanks for the details and investigation @raghavaggarwal2308! It's maybe worth mentioning again that this seems like an edge case for the permission config. 

Just my thoughts: We should consider here if the business value is relatively low for such an extensive change and that the change its self seems quite impractical as Jira instances can commonly have hundreds of projects.

**Comment by Kshitij-Katiyar** [comment] 2024-09-17 10:37
@wiggin77 @DHaussermann 
- I looked into the issue again and surprisingly I am unable to reproduce the issue with the steps I used earlier.
- I am even unable to reproduce the related issue that I reported in my last comment on this issue.
- Earlier the issue was that Jira was returning projects where the user had `create` but `no browse` permission. I checked into API response to populate the modal's dropdown and now Jira does not send the project in API response where the user does not have browse permission(which is the expected and documented behavior). A possible reason is that Jira has fixed the issue with the API response.

Please let me know If you are still able to reproduce the issue.

**Comment by raghavaggarwal2308** [comment] 2024-09-26 09:00
Closing for now, can reproduce if the issue is reproduced again

**Closed by raghavaggarwal2308** 2024-09-26 09:00 UTC
Labels: Help Wanted, Up For Grabs, Hacktoberfest, Tech/ReactJS, Tech/Go, Difficulty/2:Medium, Type/Bug
