### ISSUE TITLE
For creating issues and creating subscriptions, handle error case where issuetypes are not available

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#912] opened 2023-02-06 19:47 UTC
I enabled debug logging in MM, but apart from the get-jira-project-metadata call which returns the 500 error, I can't get any more information on the MM side.
The
```
GET /jira/rest/api/2/issue/createmeta/10200/issuetypes
```
also returns a 400 (Bad Request) when issued from Postman.
I've no idea, why this call returns an error. The corresponding project looks OK in Jira. I changed the permission theme in Jira to a relaxed one & the request worked for that project. I then changed all projects (mostly inactive ones) to a more relaxed permission scheme and voilà:

#### Conclusion
The issue is triggered by projects where the issuetypes cannot be listed due to a restrictive permission scheme.

#### Suggestion
In case of projects where the isssuetypes cannot be retrieved, an error should be logged in Mattermost, the project should not be listed in the project dropdown & the error should be handled gracefully.

#### Workaround
Make sure that the issuetypes of all projects can be listed by using a permission scheme which allows this.

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/zgocguq9wtgbtmztrctztrkrhh) *by `@jprusch`*._

**Comment by jprusch** [comment] 2023-02-06 19:55
This is also relevant for editing subscriptions (/jira subscribe edit)

**Comment by Kshitij-Katiyar** [comment] 2023-02-14 12:02
@mickmister I explored the code for this issue, read the mattermost community thread and from my understanding, the error is coming from  https://github.com/mattermost/mattermost-plugin-jira/blob/7a5c6162b49c36cffd33d61cf8ad38152c17b1ae/server/issue.go#L508 and eventually from here https://github.com/mattermost/mattermost-plugin-jira/blob/7a5c6162b49c36cffd33d61cf8ad38152c17b1ae/server/client_server.go#L178 for calling the pluginAPI ```/api/v2/get-jira-project-metadata```. For Jira server/Data Centre, It is eventually calling the API ```rest/api/2/project``` using the package (SDK) provided by the jira for golang and it is returning us the list of projects.
```type ProjectList []struct {
    Expand          string          `json:"expand" structs:"expand"`
    Self            string          `json:"self" structs:"self"`
    ID              string          `json:"id" structs:"id"`
    Key             string          `json:"key" structs:"key"`
    Name            string          `json:"name" structs:"name"`
    AvatarUrls      AvatarUrls      `json:"avatarUrls" structs:"avatarUrls"`
    ProjectTypeKey  string          `json:"projectTypeKey" structs:"projectTypeKey"`
    ProjectCategory ProjectCategory `json:"projectCategory,omitempty" structs:"projectsCategory,omitempty"`
    IssueTypes      []IssueType     `json:"issueTypes,omitempty" structs:"issueTypes,omitempty"`
}``` 

Using this we are directly getting the project list along with the issue types. If we want to get this error for a particular project then first we have to get the list project and will loop for each project key to get the issue types for each project then only we can figure out for which project we are not getting the issue types due to the permission scheme and eventually remove that project from the dropdown list. Is this approach fine?

But one small thing from the documentation of Jira I am not able to find these permission schemes which is preventing us to get the issueType for a project so that I can also reproduce this error this bug is for the Jira server/datacenter or cloud or both.

Regarding this message https://community.mattermost.com/core/pl/rziusrujzfbg9ckbcyqw98xk3r on community. Some of the APIs getting called in those logs are not getting called from our pluginAPI ```/api/v2/get-jira-project-metadata``` but from a different pluginAPI ```/api/v2/get-create-issue-metadata-for-project```. And recently there are some changes merged in that API from PR https://github.com/mattermost/mattermost-plugin-jira/pull/881. This API gets called for particular project metadata like when we select a project for creating a subscription. Should I also need to add handle this case for this pluginAPI as well? 

Please give your suggestions on this.

**Comment by mickmister** [comment] 2023-02-14 20:35
@Kshitij-Katiyar 

> first we have to get the list of projects (somehow without getting the issueType array [need to explore on this]

We can call Jira's API directly using HTTP, so hopefully it's possible through their API. I think we can limit the `expand` query parameter to not include issue types. https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-projects/#api-rest-api-2-project-search-get

>  If we want to get this error for a particular project

I think this might work:

Perform the request like we already are doing with issue types expanded.

If we run into the error (does it tell us which projects?), then fetch the projects without expanding the issue type. Then individually fetch issue types for each project. This is not performant, but may be necessary if we don't know which projects have issue types.

> This API gets called for particular project metadata like when we select a project for creating a subscription. Should I also need to add handle this case for this pluginAPI as well?

Yes the fix should be applied every place that is affected by this issue

**Comment by jprusch** [comment] 2023-02-15 11:50
Not sure, if the APIs for Jira Cloud and JIra Server/DC are same here. Please make sure something like:

https://docs.atlassian.com/software/jira/docs/api/REST/9.6.0/#api/2/project-getAllProjects

is used for server/dc.

After this the issue typed for each project can be retrieved with

https://docs.atlassian.com/software/jira/docs/api/REST/9.6.0/#api/2/issuetype

**Closed** 2023-03-03 07:17 UTC
Labels: Type/Bug
