### ISSUE TITLE
When selecting project in Create Jira Issue dialog, an error is logged in the JavaScript console

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#172] opened 2019-06-15 01:01 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

**Repro steps**:
1. Enable and configure the plugin using steps at https://github.com/mattermost/mattermost-plugin-jira
2. Use "/jira connect" to connect your Mattermost account with Jira
3. Complete the connection flow
4. Hover over a message, click on the "More Actions" (...) menu, then select "Create Jira Issue".

Observed: JavaScript error in the console
![image](https://user-images.githubusercontent.com/13119842/59545077-7c915680-8ee7-11e9-8090-15d0c176bc98.png)

Expected: No error.

Potential cause: We are setting state outside of where we're supposed to in the React lifecycle.

**Comment by jfrerich** [comment] 2020-01-21 03:23
This issue is no longer reproducible.  Both @jasonblais and @jfrerich attempted to repro.  The suspicion is that the bug was solved sometime since the ticket was created.  Closing.

**Closed by jfrerich** 2020-01-21 03:23 UTC
Labels: Bug, Help Wanted, Tech/JavaScript, Tech/ReactJS
