### ISSUE TITLE
jira Search logic issue

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-jira#825] opened 2021-12-06 19:45 UTC
1) when i type "an" in the small or capital latter then i'm not getting the right result.
2) **but when i add 3rd character as "-" then i got some result but still if **i got that result as "AN-13:dsd"** then why i did not got the this (AN-12:test) issue in the List.**
there is some issue in the search logic.
https://user-images.githubusercontent.com/89907719/144911424-54d52f32-1bec-4178-b795-752ed4f060d7.mp4

**Comment by sibasankarnayak** [comment] 2022-01-26 13:12
@mickmister was looking into the logic , current jira search issue is totally dependent on this function https://github.com/mattermost/mattermost-plugin-jira/blob/b62a305174963133cfc219a6a0a2132997f75118/server/client.go#L194 tried the reproduce the same issue with same steps mentioned but got the result from jira plugin function 
this seems to be a issue jira package which we are using.


cc @dipak-demansol

**Comment by mickmister** [comment] 2022-01-26 18:31
@sibasankarnayak Sorry I meant to close this ticket earlier

The expected behavior of Jira itself is that you cannot search for issues by a partial match of issue key. If you want to search for an issue by its issue key, you have to type in the exact key.

What's happening in the linked video:

- User types `AN-`
- Jira searches for issues that match this search. This search does not include matching on issue keys at all.
- Issue `AN-13` contains in its _description_ a link to another ticket that has prefix `AN-`, and this is what makes it show up in the search results, since the text-based search matched this text.

The behavior shown in the video is expected, since there is no partial match searching on issue keys. It is a coincidence that given a partial search on an issue key, that any results showed up at all.

**Closed by mickmister** 2022-01-26 18:31 UTC
Labels: Type/Bug

**Comment by mickmister** [comment] 2022-01-26 18:32
@dipak-demansol Thanks for reporting this. Please let me know if the above comment makes sense.

**Comment by dipak-demansol** [comment] 2022-01-26 18:46
> @dipak-demansol Thanks for reporting this. Please let me know if the above comment makes sense.

@mickmister thanks for the info, i learned something new :)
