### ISSUE TITLE
/jira connect fails to load page after login succeded

### ISSUE THREAD

**Issue by ticpu** [mattermost/mattermost-plugin-jira#936] opened 2023-05-01 15:00 UTC
We just migrated to jira cloud and after uninstalling the server URL and installing the cloud URL, the login works but then I get to a page called "User mapping and configuration page" which loads for a bit and fails.

Here is the console log for that:
![image](https://user-images.githubusercontent.com/1229687/235472679-5481754b-40b5-44be-8f7d-d5533ce9455b.png)

* POST https://o55978.ingest.sentry.io/api/5988809/envelope/?sentry_key=12742a0abbd1484686195dca8ba74be6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.47.0 net::ERR_NAME_NOT_RESOLVED
* GET https://cauca.atlassian.net/gateway/api/watermelon/organization/containsAnyWorkspace?cloudId=a01c8563-1915-4718-9785-220ca688f03f 404
* Refused to display 'https://chat.cauca.ca/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

The reload page button contains this link:
https://cauca.atlassian.net/plugins/servlet/ac/mattermost_https_chat_cauca_ca/user-redirect?mm_token=(some secret token)

Edit: added the 3 errors in text too and reload link.

**Comment by mickmister** [comment] 2023-05-01 15:28
Hi @ticpu, thanks for creating this issue :+1:

This issue may be related to the errors in the screenshot, but it's hard to tell. Either way, there's not enough information for me to know the root cause here. Are there any errors containing your Mattermost server's Site URL?

FYI, we're deprecating this method of connecting to Jira Cloud, in favor of Jira Cloud's OAuth offering https://github.com/mattermost/mattermost-plugin-jira/pull/928

**Comment by ticpu** [comment] 2023-05-01 15:55
I will try to relink the instance and see if there's any log I missed.  The install part did go without any issue, it's really when I'm usr /jira connect that it fails.
If there's any version ready that you'd like me to test for the OAuth 2 enabled plugin, I'd be more than happy to try it out.

**Comment by ticpu** [comment] 2023-05-01 19:18
I did try installing /jira setup this time, the process was similar and I think the only time there's a reference to our Mattermost server's URL is when adding the application.  When using /jira connect I think it doesn't get far enough in the process to callback our MM server.

**Comment by mickmister** [comment] 2023-05-02 20:12
@ticpu Hmm I'm not sure what's going on here. I'm open to having a video call to investigate this more if you would like. If you want to have a call, can you please create an account at https://community.mattermost.com and DM me at `@michael.kochell`

**Comment by mickmister** [comment] 2023-05-04 20:06
@ticpu and I discussed offline and determined the issue was with an nginx proxy in front of Mattermost setting the header `X-Frame-Options` `sameorigin`. Removing this header modification fixed the issue.

Closing the issue since it's now resolved. Also, as mentioned in https://github.com/mattermost/mattermost-plugin-jira/issues/936#issuecomment-1529836575, we are moving to an OAuth-based solution where this iframe issue will not occur.

**Closed as completed by mickmister** 2023-05-04 20:06 UTC
