### ISSUE TITLE
Reporter is missing when user completes issue save in Jira (cloud only)

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#675] opened 2020-09-28 20:28 UTC
There is an issue when a task has unsupported custom fields and the user must navigate to Jira to finish saving their issue. 
In this case, once the user navigates to Jira, the reporter field is empty instead of being set to the current user. 
This happens on Jira Cloud only. Server instances to not seem affected. 
I don't believe that this is a regression from Jira 2.4

Steps:
- Configure a Jira project such that an unsupported custom field is mandatory (ex: Radio button)
- Connect test user from Mattermost     
- Create a Jira issue from a post
- Add detail in the modal and save
- Click the link that is created to complete issue creation in Jira

**Observed** When you navigate to Jira, the Reporter field is empty.

**Comment by raghavaggarwal2308** [comment] 2024-07-25 11:08
@DHaussermann I tried to reproduce this issue but I was unable to do so, the reported field was getting set to the current user once we complete creating the issue on Jira. 
Post with the link:
![image](https://github.com/user-attachments/assets/71164bf7-131f-4152-a05c-2c8578c1c0c4)

Completing issue on Jira:
![image (1)](https://github.com/user-attachments/assets/5db8f029-c573-4344-b177-fb127f9c9f7c)

Reporter asigned:
![image (2)](https://github.com/user-attachments/assets/b34fbf5b-37f4-4790-adca-0c73f301885c)

I did notice that on the issue completing page the reported field was not visible, that might have caused the confusion. Or the issue might have been fixed with some other PR.

Closing for now. Please feel free to re-open it if I missed something and the issue is still reproducible.

**Closed by raghavaggarwal2308** 2024-07-25 11:08 UTC
Labels: Type/Bug
